config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "pages#show", page: "home"

  get  '/component/:id', to: 'pages#component', as: 'component'
  get  '/components/', to: 'pages#components', as: 'components'
  get  '/contentmapping', to: 'pages#contentmapping'
  get  '/home', to: 'pages#home'
  get  '/flows', to: 'pages#flows'
  get  '/flowdetail/:id', to: 'pages#flowdetail', as: 'flowdetail'
  get  '/iframe', to: 'pages#iframe', as: 'iframe'
  get  '/legacysites', to: 'pages#legacysites'
  get  '/legacysitedetail/:id', to: 'pages#legacysitedetail', as: 'legacysitedetail'
  get  '/messaging', to: 'pages#messaging'
  get  '/messagingdetail/:id', to: 'pages#messagingdetail', as: 'messagingdetail'
  get  '/personachart/', to: 'pages#personachart', as: 'personachart'
  get  '/page/:id', to: 'pages#page', as: 'page'
  get   "/pages/:page" => "pages#show"
  get  '/searchtest', to: 'pages#searchtest'
  resources :search, only: [:index]
  resources :site_crawl
  get  '/sitemap', to: 'pages#sitemap'
  get  '/sitemapdetail/:id', to: 'pages#sitemapdetail', as: 'sitemapdetail'
  resources :sitepage
  get  '/smart_listing/' => 'smart_listing#index'
  get  '/taxonomy', to: 'pages#taxonomy'
  get  '/taxonomysite/:id', to: 'pages#taxonomysite', as: 'taxonomysite'
  get  '/templates', to: 'pages#templates'
  get  '/templatedetail/:id', to: 'pages#templatedetail', as: 'templatedetail'
  get  '/templatelist/:id', to: 'pages#templatelist', as: 'templatelist'
  resources :text_item
  get 'tree/' => 'tree#index'
  get 'tree/data', :defaults => { :format => 'json' }
  get 'tree/jcitags', :defaults => { :format => 'json' }
  get 'tree/tycotags', :defaults => { :format => 'json' }
  get 'tree/jcimap', :defaults => { :format => 'json' }
  get 'tree/tycomap', :defaults => { :format => 'json' }
  get  '/api/v1/tag/data', :defaults => { :format => 'json' }
  get  '/webfootprint', to: 'pages#webfootprint'
  #api
  namespace :api do
    namespace :v1 do
      # resources :sessions, only: [:create, :show]
      resources :tag, only: [:index, :create, :show, :update, :destroy] do
        post :activate, on: :collection
        # resource :feed, only: [:show]
      end
    end
  end

end

app/views/pages/_archive_templates.html.erb
  <div class="row">
		<div class="col-sm-4">
      <%= render "siteContentModel" %>

        <div class="well">
    			<h3>What is a Content Model?</h3>
          <p>A Content Model the result of business requirements and design decisions. It captures several elements that make up the digital experience:</p>
          <ul>
            <li>Page templates</li>
            <li>Components that make up each template</li>
            <li>Attributes of each component</li>
            <li>Intent, logic and rules for page templates, components and attributes</li>
          </ul>
        </div>
		</div>
		<div class="col-sm-8">
			<h1>Content Model</h1>

      <% @templates = ::Template.order(:name) %>

      <% @templates.each do |templateitem|  %>
      <div class="row">
        <div class="col-8 col-sm-8">
          <div class="card border-secondary mb-3">
            <h3 class="card-header"><%= link_to templateitem.name, templatedetail_path(templateitem) %>
              <% if templateitem.existing == true %>
              <span class="badge badge-light">Existing</span>
              <% else %>
              <% end %>
              <small class="text-muted">Page Template</small>
            </h3>
            <ul class="list-group list-group-flush">
              <li class="list-group-item disabled">Components</li>
              <% templateitem.components.each do |n| %>
              <li class="list-group-item"><%= n.name %>
                <% if n.existing == true %>
                <span class="badge badge-light">Existing</span>
                <% else %>
                <% end %>
              </li>
              <% end %>
            </ul>
          </div>
        </div>
        <div class="col-8 col-sm-2">
          <img style="margin-top:30px;" src="<%= templateitem.image %>" height="200">
        </div>
      </div>

      <% end %>
    </div>

		</div>
	</div>
  	<hr>
  <div class="row">
    <div class="col-xs-12">
      <footer>
        <p>Content Model v.0.1</p>
      </footer>
    </div>
  </div>

app/views/pages/_siteMessaging.html.erb
<div class="well">
    View for&nbsp;
      <% @sites = ::Site.order(:name) %>
      <% @sites.each do |site|  %>
        <%= link_to site.name, messagingdetail_path(site) %>&nbsp;&nbsp;
      <% end %>
</div>

app/views/pages/_siteTaxonomy.html.erb
    <% @sites = ::Site.order(:name) %>
    <%# @sites.each do |site|  %>
      <%#= link_to site.name, taxonomysite_path(site) %>&nbsp;&nbsp;
    <%# end %>

app/views/pages/code_snips.html.erb
<!-- ## CODE SNIPS  ## -->

<!-- # for generating a styled list tree, from app/views/pages/taxonomysite.html.erb -->

<% @sitetags = Tag.joins( :site_tag_mappings ).where( site_tag_mappings: { site_id: (params[:id]) }) %>
<% @tags = @sitetags.arrange %>
<%= arranged_tree_as_list(@tags, {:list_style => :bootstrap_list_group}) do |tag| %>

    <%= tag.name %>

<% end %>

<!-- # for generating a styled sitemap tree, from app/views/pages/sitemapdetail.html.erb -->
<% @sitepages = Page.where( site_id: (params[:id]) ) %>
        <% @pages = @sitepages.arrange %>
        <%= arranged_tree_as_list(@pages, {:list_style => :bootstrap_list_group}) do |page| %>

            <%= link_to page.name, page_path(page.id) %>

        <% end %>

app/views/pages/components.html.erb
<% @site = Site.find(1) %>

  <div class="row">
		<div class="col-sm">

			<h1><%#= @site.name %><small class="text-muted"> Components</small></h1>

        <hr>
        <!-- IN PROGRESS PILL NAV FILTER LISTING BY GROUP -->
        <% @componentgroups = ComponentGroup.all %>
        <!-- <ul class="nav nav-pills">
          <% @componentgroups.each do |group| %>
          <li class="nav-item">
            <a class="nav-link disabled" href="#"><%= group.name %></a>
          </li>
          <% end %>
        </ul> -->

    </div>
  </div>




        <% @components = Component.all.order('name ASC') %>
        <% @components.each do |component| %>
        <% @templates = TemplateComponent.order(:position).includes(:component, :template).references(:component, :template).where ({component_id: component.id})  %>
  <div class="row">
          <div class="col-sm-3">
            <p>Applies to Templates:<br>
              <%#= safe_join ( @templates.all.map { |x| [link_to(x.template.name, templatedetail_path(id: => x.template.id, site: => @site.id)),"<br>".html_safe] }) %>
              <% @templates.each do |t| %>
                <%= link_to t.template.name, templatedetail_path(:id => t.template.id, :site => @site.id) %><br>
                <% end %>
          </div>
          <div class="col-sm-4">
            <h5><%= component.name %> <span class="badge badge-pill badge-secondary"><%= component.component_group.name %></span></h5>
            <table class="table table-striped">
            <tbody>
            <% if component.invision_link.blank? %>
            <% else %>
            <tr>
              <td valign="top" colspan="2"><small class="text-muted"><%= link_to "Invision Link", component.invision_link, target: "_blank" %></small></td>
            </tr>
            <% end %>

            <% if component.image_sizes.blank? %>
            <% else %>
            <tr>
              <td valign="top"><small class="text-muted"><strong>Image Sizes</strong></small></td>
              <td valign="top"><small class="text-muted"><%= component.image_sizes %></small></td>
            </tr>
            <% end %>

            <% if component.page.blank? %>
            <% else %>
            <tr>
              <td valign="top"><small class="text-muted"><strong>Page</strong></small></td>
              <td valign="top"><small class="text-muted"><%= component.page %></small></td>
            </tr>
            <% end %>

            <% if component.requirements.blank? %>
            <% else %>
            <tr>
              <td valign="top"><small class="text-muted"><strong>Requirements</strong></small></td>
              <td valign="top"><small class="text-muted"><%=raw component.requirements %></small></td>
            </tr>
            <% end %>

            <% if component.interaction_notes.blank? %>
            <% else %>
            <tr>
              <td valign="top"><small class="text-muted"><strong>Interaction Notes</strong></small></td>
              <td valign="top"><small class="text-muted"><%=raw component.interaction_notes %></small></td>
            </tr>
            <% end %>

            <% if component.full_width.blank? %>
            <% else %>
            <tr>
              <td valign="top"><small class="text-muted"><strong>Full Width:</strong></td>
              <td valign="top"><small class="text-muted"><% if component.full_width == 1 %>Yes<% else %>No<% end %></small></td>
            </tr>
            <% end %>

            <% if component.personalization_rules.blank? %>
            <% else %>
            <tr>
              <td valign="top"><small class="text-muted"><strong>Personalization</strong></small></td>
              <td valign="top"><small class="text-muted"><%=raw component.personalization_rules %></small></td>
            </tr>
            <% end %>

            <% if component.data.blank? %>
            <% else %>
            <tr>
              <td valign="top"><small class="text-muted"><strong>Data</strong></small></td>
              <td valign="top"><small class="text-muted"><%=raw component.data %></small></td>
            </tr>
            <% end %>

            <% if component.allowed_controls.blank? %>
            <% else %>
            <tr>
              <td valign="top"><small class="text-muted"><strong>Allowed Controls</strong></small></td>
              <td valign="top"><small class="text-muted"><%=raw component.allowed_controls %></small></td>
            </tr>
            <% end %>

            <% if component.need_info.blank? %>
            <% else %>
            <tr>
              <td valign="top"><small class="text-muted"><strong>Need Info</strong></small></td>
              <td valign="top"><small class="text-muted"><% if component.need_info == "x" %>Yes<% else %>No<% end %></small></td>
            </tr>
            <% end %>

            <% if component.design_questions.blank? %>
            <% else %>
            <tr>
              <td valign="top"><small class="text-muted"><strong>Design Questions</strong></small></td>
              <td valign="top"><small class="text-muted"><%=raw component.design_questions %></small></td>
            </tr>
            <% end %>

            <% if component.dev_notes.blank? %>
            <% else %>
            <tr>
              <td valign="top"><small class="text-muted"><strong>Dev Notes</strong></small></td>
              <td valign="top"><small class="text-muted"><%=raw component.dev_notes %></small></td>
            </tr>
            <% end %>

          </tbody>
          </table>
          </div>
          <div class="col-sm-5">
            <% component.images.each do |image| %>
              <small class="text-muted"><strong><%= image.name %></strong><br>
              <%= image.description %><br>
              <%= image_tag(image.image_url, style: 'height:auto;width:100%;') %></small><br>
            <% end %>

            <% if component.image.blank? %>
            <% else %>
            <img alt="<%= component.image %>" src="http://contentmodel-jci-assets.s3.amazonaws.com/images/components/<%= component.image %>" width="100%">
            <% end %>
          </div>
	</div>
  <hr>
            <% end %>



  <div class="row">
    <div class="col-sm">

              <%= render "footer" %>

    </div>
  </div>

app/views/pages/iframe.html.erb
<%# @site = Site.find(params[:id]) %>
<%#= content_tag "div", id: "site", data: {site: @site.id} do %>
<%# end %>
<%#= content_tag "div", id: "type", data: {type: "taxonomy"} do %>
<%# end %>

  <div class="row">

		<div class="col-sm">


			<h1>iFrame Test</h1>

      <%#= render "siteTaxonomy" %>
      <iframe style="width:100%; height:900px; margin: 0 0 30px 0; border:#ccc 1px dotted;" src="https://rightpoint.com">
        <p>Placeholder text; only shows up if the page DOESN'T render!</p>
      </iframe>


		</div>
	</div>
  	<hr>
  <div class="row">
    <div class="col-sm">

        <%= render "footer" %>

    </div>
  </div>

app/views/pages/legacysitedetail.html.erb
<% @thislegacysite = LegacySite.find(params[:id])%>

  <div class="row">
		<div class="col-xs-12">
      <div class="alert alert-warning" role="alert">
        This page is under development for information display.
      </div>
			<h1><%= @thislegacysite.name %></h1>
      <% @sitepages = SiteCrawl.order(:address).where site_id: (params[:id]) %>
      <table class="table table-hover">
        <thead>
          <tr>
            <th scope="col">Retain</th>
            <th scope="col">Update</th>
            <th scope="col">Retire</th>
            <th scope="col">Page</th>
            <th scope="col">ID</th>
          </tr>
        </thead>
        <tbody>

        <% @sitepages.each do |site|  %>
        <tr>
          <td>select</td>
          <td>select</td>
          <td>select</td>
          <td><%= link_to truncate(site.address, :length => 100), site.address, target: :_blank %></td>
          <td><%= site.id %></td>
        </tr>

        <% end %>
        </tbody>
      </table>

		</div>
	</div>
  	<hr>
  <div class="row">
    <div class="col-xs-12">

              <%= render "footer" %>

    </div>
  </div>

app/views/pages/page.html.erb
<% @thispage = Page.find(params[:id])
   @site = Site.find(params[:site])





    %>
  <!-- <div class="row">
    <div class="col-sm">
      <div class="alert alert-warning" role="alert">
        This page is under development for information display.
      </div>
    </div>
  </div> -->
  <div class="row">
		<div class="col-sm-3">

            <%= render "siteMap" %>

      <!-- <p>User Workflow > Template
      <p>Breadcrumbs > Information Architecture path
        <hr> -->


          <% @thispage.templates.each do |b| %>

          <h5>Template</h5>
          <p><%= link_to b.name, templatedetail_path(:id => b.id, :site => @site.id) %></p>

              <!-- display Messaging Hierarchy assigned to the template for this page -->
              <% b.hierarchies.each do |h| %>
                <h5>Messaging</h5>
                <strong class="text-muted"><%= h.name %></strong>
                <p><small class="text-muted"><%= h.description %></small></p>
              <% end %>
          <% end %>

      <% @thispage.templates.each do |a| %>
      <h5>Template Components</h5>
        Click to view detail and customize template content for page.</small>

        <% @cinstance = TemplateComponent.order(:position).includes(:component, :template).references(:component, :template).where ({template_id: a.id}) %>
        <ol>
          <!-- top version includes component instance ID for debugging -->
          <%#= safe_join ( @cinstance.all.map { |x| ["<li>".html_safe, x.id, " ", link_to(x.component.name, text_item_index_path(:id => x.component.id, :instance => x.id, :template => x.template.id, :page => @thispage.id, :site => @site.id)),"</li>".html_safe] }) %>
          <%= safe_join ( @cinstance.all.map { |x| ["<li>".html_safe, link_to(x.component.name, text_item_index_path(:id => x.component.id, :instance => x.id, :template => x.template.id, :page => @thispage.id, :site => @site.id)),"</li>".html_safe] }) %>
        </ol>
      <% end %>

      <!-- <h3>Desired Actions</h3> -->
		</div>
		<div class="col-sm-9">
      <!-- hack to display the page name if not yet associated with a template (all pages should be associated with a template) -->
      <% if @thispage.templates.empty? %>
        <h1><%= @thispage.name %></h1>
        <p class="text-muted">This page requires template and content configuration.</p>
      <% end %>

      <% @thispage.templates.each do |c| %>

      <h1><%= @thispage.name %></h1>

            <hr>

      <h5>Tags</h5>
      <% @pagetags = TagMapping.where page_id: (params[:id]) %>
        <% if @pagetags.empty? %>
          <p class="text-muted">No tags assigned.</p>
        <% end %>
      <% @pagetags.each do |t| %>
            <a href="#" class="badge badge-info"><%= t.tag.name %></a>
      <% end %>
        <hr>
      <!-- <h5>SEO Terms</h5>
      <%# @pageterms = SeoMapping.where page_id: (params[:id]) %>
        <%# if @pageterms.empty? %>
          <p class="text-muted">No SEO terms assigned.</p>
        <%# end %>
      <%# @pageterms.each do |s| %>
          <%#= s.term.name + (", ").html_safe %>
      <%# end %>
            <%#= form_with model: @page do |f| %>
                  <%#= f.hidden_field :page_id, value: @thispage.id %>
                  <div class="row">
                    <%#= f.label :terms %>
                    <%#= f.select :seo_term_id,
                      SeoTerm.all.map { |k| [k.term, k.id] },
                                      { include_blank: true },
                                      { :multiple => true, class: 'chosen-select' }
                    %>
                  </div>

                  <div class="row">
                    <%#= f.submit "Save Terms" %>
                  </div>
            <%# end %>

        <hr>-->


      <h5>Page Content</h5>


      <% @cinstance.each do |pc| %>
      <% @pagetext = TextItem.order(:order).includes(:component).references(:component).where ({page_id: @thispage.id, component_id: pc.component.id, template_component_id: pc.id}) %>

      <div class="card-group">

        <% case pc.component.name %>
        <% when "Product Card" %>
            <div class="card" style="margin-bottom:15px;">
              <div class="card-body">
                <%= link_to pc.component.name, text_item_index_path(:id => pc.component.id, :instance => pc.id, :template => pc.template.id, :page => @thispage.id, :site => @site.id), :class => "badge badge-secondary", :style => "margin-bottom:10px;",  :title => "Edit "+pc.component.name %></br>
                <% @pagetext.each do |pt| %>
                  <!-- <small class="text-muted">TextInstanceID <%=pt.id %></small></br> -->
                  <<%= pt.text.name %>><%#= pt.order %><%= pt.itemtext %></<%= pt.text.name %>
                <% end %>
              </div>
            </div>
        <% when "Solution Card" %>
            <div class="card" style="margin-bottom:15px;">
              <div class="card-body">
                <%= link_to pc.component.name, text_item_index_path(:id => pc.component.id, :instance => pc.id, :template => pc.template.id, :page => @thispage.id, :site => @site.id), :class => "badge badge-secondary", :style => "margin-bottom:10px;",  :title => "Edit "+pc.component.name %></br>
                <% @pagetext.each do |pt| %>
                  <!-- <small class="text-muted">TextInstanceID <%=pt.id %></small></br> -->
                  <<%= pt.text.name %>><%#= pt.order %><%= pt.itemtext %></<%= pt.text.name %>>
                <% end %>
              </div>
            </div>


        <% else %>

          <div class="card" style="margin-bottom:15px;">
            <div class="card-body">
            <!-- <small class="text-muted">ComponentInstanceID <%= pc.id %> | PageID <%= @thispage.id %></small></br> -->
              <%= link_to pc.component.name, text_item_index_path(:id => pc.component.id, :instance => pc.id, :template => pc.template.id, :page => @thispage.id, :site => @site.id), :class => "badge badge-secondary", :style => "margin-bottom:10px;", :title => "Edit "+pc.component.name %></br>
              <% @pagetext.each do |pt| %>
                <!-- <small class="text-muted">TextInstanceID <%=pt.id %></small></br> -->
                <small class="text-muted">Character Count: <%= pt.itemtext.size %></small><br>
                <<%= pt.text.name %>><%#= pt.order %><%= pt.itemtext %></<%= pt.text.name %>>
            <% end %>
            </div>
          </div>

        <% end %>
      </div>
      <% end %>

      <!-- below is the closing tag for the templates.each do |c| -->
      <% end %>
		</div>
	</div>
  	<hr>
  <div class="row">
    <div class="col-sm">

              <%= render "footer" %>

    </div>
  </div>

app/views/pages/site.html.erb
  <div class="row">
		<div class="col-xs-4">
      <p>Johnson Controls > JohnsonControls.com
        <hr>
			<h3>Notes</h3>

		</div>
		<div class="col-xs-8">
			<h1>Sitemap</h1>



        <% @pages = Page.arrange %>

        <%= arranged_tree_as_list(@pages, {:list_style => :bootstrap_list_group}) do |page| %>

            <%= page.name %>

        <% end %>


		</div>
	</div>
  	<hr>
  <div class="row">
    <div class="col-xs-12">
      <footer>
        <p>Content Model v.0.1</p>
      </footer>
    </div>
  </div>

app/views/pages/sitemap.html.erb
  <div class="row">
		<div class="col-sm-3">



			<h3>Notes</h3>

		</div>
		<div class="col-sm-9">
			<h1>Site Map</h1>
      <%= render "siteMap" %>




		</div>
	</div>
  	<hr>
  <div class="row">
    <div class="col-sm">

              <%= render "footer" %>

    </div>
  </div>

app/views/pages/sitemapdetail.html.erb
<% @site = Site.find(params[:id]) %>

<%= content_tag "div", id: "site", data: {site: @site.id} do %>
<% end %>
<%= content_tag "div", id: "type", data: {type: "sitemap"} do %>
<% end %>

  <div class="row">
		<div class="col-sm">

      <%= render "siteMap" %>

      <nav>
        <div class="nav nav-tabs justify-content-center" id="nav-tab" role="tablist">
          <% @sites.each do |sitetab|  %>
            <% if sitetab.id == @site.id %>
              <small><a class="nav-item nav-link active" id="nav-<%= sitetab.id %>-tab" data-toggle="tab" href="/sitemapdetail/<%= @site.id %>" role="tab" aria-controls="nav-<%= sitetab.id %>" aria-selected="true"><%= sitetab.name %></a></small>
            <% else %>
              <small><a class="nav-item nav-link" id="nav-<%= sitetab.id %>-tab" href="/sitemapdetail/<%= sitetab.id %>" role="tab" aria-controls="nav-<%= sitetab.id %>" aria-selected="false"><%= sitetab.name %></a></small>
            <% end %>
          <% end %>
        </div>
      </nav>



      <h1 style="margin-top: 20px">Site Map<small class="text-muted"> <%= @site.name %></small></h1>


      <small class="text-muted">Click any circle to expand an item. Click and drag the visualization to pan up and down, right and left. Use the mouse wheel to zoom in and out.</small>

      <div class="tab-content" id="nav-tabContent">
          <% @sites.each do |sitecontent|  %>
            <% if sitecontent.id == @site.id %>
              <div class="tab-pane fade show active" id="nav-<%= sitecontent.id %>" role="tabpanel" aria-labelledby="nav-<%= sitecontent.id %>-tab">
                <div id="tree"></div>
              </div>
            <% end %>
          <% end %>
<!-- </div>   -->         

		</div>
	</div>
  	<hr>
  <div class="row">
    <div class="col-sm">

              <%= render "footer" %>

    </div>
  </div>

app/views/pages/taxonomysite.html.erb
<% @site = Site.find(params[:id]) %>
<%= content_tag "div", id: "site", data: {site: @site.id} do %>
<% end %>
<%= content_tag "div", id: "type", data: {type: "taxonomy"} do %>
<% end %>

  <div class="row">

		<div class="col-sm">


      <%= render "siteTaxonomy" %>

      <nav>
        <div class="nav nav-tabs justify-content-center" id="nav-tab" role="tablist">
          <% @sites.each do |sitetab|  %>
            <% if sitetab.id == @site.id %>
              <small><a class="nav-item nav-link active" id="nav-<%= sitetab.id %>-tab" data-toggle="tab" href="/taxonomysite/<%= @site.id %>" role="tab" aria-controls="nav-<%= sitetab.id %>" aria-selected="true"><%= sitetab.name %></a></small>
            <% else %>
              <small><a class="nav-item nav-link" id="nav-<%= sitetab.id %>-tab" href="/taxonomysite/<%= sitetab.id %>" role="tab" aria-controls="nav-<%= sitetab.id %>" aria-selected="false"><%= sitetab.name %></a></small>
            <% end %>
          <% end %>
        </div>
      </nav>   


			<h1 style="margin-top: 20px">Taxonomy<small class="text-muted"> <%= @site.name %></small></h1>


      
      <small class="text-muted">Click any circle to expand an item. Click and drag the visualization to pan up and down, right and left. Use the mouse wheel to zoom in and out.</small>

      <div class="tab-content" id="nav-tabContent">
          <% @sites.each do |sitecontent|  %>
            <% if sitecontent.id == @site.id %>
              <div class="tab-pane fade show active" id="nav-<%= sitecontent.id %>" role="tabpanel" aria-labelledby="nav-<%= sitecontent.id %>-tab">
                <div id="tree"></div>
              </div>
            <% end %>
          <% end %>
      </div>




		</div>
	</div>
  	<hr>
  <div class="row">
    <div class="col-sm">

        <%= render "footer" %>

    </div>
  </div>

app/views/pages/templatelist.html.erb
<% @site = Site.find(params[:id]) %>
<% @templatelist = ::Template.joins( :site_template_mappings ).where( site_template_mappings: { site_id: (params[:id]) }).order(:name) %>

  <div class="row">
    <!-- left column -->
		<div class="col-sm-3">

      <%= render "siteContentModel" %>

      <hr>

      <h5>Template Index</h5>

      <ol>
  <% @templatelist.each do |tl| %>
        <li>

          <%= link_to tl.name, templatedetail_path(:id => tl.id, :site => @site.id) %>

        </li>
        <% end %>
      </ol>

      <%= render "contentmodelgroups" %>


		</div>
    <!-- right column -->
		<div class="col-sm-9">
      <h1>Templates<small class="text-muted"> <%= @site.name %></small></h1>
      <%= link_to "Visual Design Table of Contents", "https://rightpoint.invisionapp.com/share/T2MSV1YYPS4#/screens/299954157_TOC", :class => "btn btn-info", target: "_blank" %>


          <p>

            <div class="container-fluid mt-4">
            <div class="row justify-content-center">

                  <% @templatelist.each do |tl| %>
                  <div class="col-auto mb-3">
                    <div class="card" style="width: 15rem;">

                    <div class="card-body">
                    <%= link_to tl.name, templatedetail_path(:id => tl.id, :site => @site.id) %>

                        <% @cinstance = TemplateComponent.order(:position).includes(:component, :template).references(:component, :template).where ({template_id: tl.id}) %>

                        <% @cinstance.each do |c| %>
                          <div style="margin-bottom:1px; padding-left:5px;background-color:<%= c.component.component_group.color %>;">
                            <small><%= c.component.name %></small>

                          </div>
                        <% end%>
                      </div>

                    </div>
                  </div>
                  <% end %>
            </div>
            </div>





    </div>




    </div>



  	<hr>
  <div class="row">
    <div class="col-sm">

        <%= render "footer" %>

    </div>
  </div>

app/views/pages/workflows.html.erb
  <div class="row">
		<div class="col-xs-4">

      <%= render "siteWorkflow" %>


        <hr>
			<h3>Notes</h3>


		</div>
		<div class="col-xs-8">
			<h1>Site Flows</h1>

      <% @flows = Flow.order(:name) %>
      <% @flows.each do |flow|  %>
      <h5><%= flow.name %></h5>
      <p>
        <%= safe_join(flow.templates.map { |d| link_to(d.name, templatedetail_path(d, flow: flow.id), :class => "btn btn-info align-center") }, "&nbsp;&nbsp;>&nbsp;&nbsp;".html_safe) %>
      </p>
      <% end %>


		</div>
	</div>
  	<hr>
  <div class="row">
    <div class="col-xs-12">
      <footer>
        <p>Content Model v.0.1</p>
      </footer>
    </div>
  </div>