config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "pages#show", page: "home"

  get  '/component/:id', to: 'pages#component', as: 'component'
  get  '/components/', to: 'pages#components', as: 'components'
  get  '/contentmapping', to: 'pages#contentmapping'
  get  '/home', to: 'pages#home'
  get  '/flows', to: 'pages#flows'
  get  '/flowdetail/:id', to: 'pages#flowdetail', as: 'flowdetail'
  get  '/iframe', to: 'pages#iframe', as: 'iframe'
  get  '/legacysites', to: 'pages#legacysites'
  get  '/legacysitedetail/:id', to: 'pages#legacysitedetail', as: 'legacysitedetail'
  get  '/messaging', to: 'pages#messaging'
  get  '/messagingdetail/:id', to: 'pages#messagingdetail', as: 'messagingdetail'
  get  '/personachart/', to: 'pages#personachart', as: 'personachart'
  get  '/page/:id', to: 'pages#page', as: 'page'
  get   "/pages/:page" => "pages#show"
  get  '/searchtest', to: 'pages#searchtest'
  resources :search, only: [:index]
  resources :site_crawl
  get  '/sitemap', to: 'pages#sitemap'
  get  '/sitemapdetail/:id', to: 'pages#sitemapdetail', as: 'sitemapdetail'
  resources :sitepage
  get  '/smart_listing/' => 'smart_listing#index'
  get  '/taxonomy', to: 'pages#taxonomy'
  get  '/taxonomysite/:id', to: 'pages#taxonomysite', as: 'taxonomysite'
  get  '/templates', to: 'pages#templates'
  get  '/templatedetail/:id', to: 'pages#templatedetail', as: 'templatedetail'
  get  '/templatelist/:id', to: 'pages#templatelist', as: 'templatelist'
  resources :text_item
  get 'tree/' => 'tree#index'
  get 'tree/data', :defaults => { :format => 'json' }
  get 'tree/jcitags', :defaults => { :format => 'json' }
  get 'tree/tycotags', :defaults => { :format => 'json' }
  get 'tree/jcimap', :defaults => { :format => 'json' }
  get 'tree/tycomap', :defaults => { :format => 'json' }
  get  '/api/v1/tag/data', :defaults => { :format => 'json' }
  get  '/webfootprint', to: 'pages#webfootprint'
  #api
  namespace :api do
    namespace :v1 do
      # resources :sessions, only: [:create, :show]
      resources :tag, only: [:index, :create, :show, :update, :destroy] do
        post :activate, on: :collection
        # resource :feed, only: [:show]
      end
    end
  end

end

app/models/text_item.rb
class TextItem < ApplicationRecord
  belongs_to :text, optional: true
  belongs_to :page, optional: true
  belongs_to :component, optional: true
end

app/controllers/text_item_controller.rb
class TextItemController < ApplicationController
  respond_to :html
  respond_to :js


  def index
    @textitems = TextItem.all
    @textitem = TextItem.new
    @textitemstemplate = TextItem.where page_id: nil
    @textitemspage = TextItem.where page_id: params[:page]

  end

  def show
       # render js: "alert('The number is: #{params[:id]}')"
  end

    def create
      @textitem = TextItem.create!(allowed_params)

      # redirect_to text_item_url
      # redirect_to "/text_item/"
      respond_to do |f|
        f.html { redirect_to text_item_index_path }
        f.js
      end      # @textitem = TextItem.new(params[:textitem])
      #
      # respond_to do |format|
      #   if @textitem.save
      #     format.html { redirect_to @textitem, notice: 'Item was successfully created.' }
      #     format.js
      #     format.json { render json: @textitem, status: :created, location: @textitem_url
  end

  def update
     @textitem = TextItem.find(params[:id])
     @textitem.update_attributes!(allowed_params)

     respond_to do |f|
       # f.html { redirect_to "/text_item/" }
       f.html {redirect_to text_item_index_path}
       f.js
     end
  end

  def destroy
    @textitem = TextItem.destroy(params[:id])

    # redirect_to text_item_index_path
    respond_to do |f|
      f.html { redirect_to text_item_index_path(:id => params[:component], :instance => params[:instance], :template => params[:template], :page => params[:page], :site => params[:site]) }
      f.js
    end
  end

  private

  def allowed_params
    params.require(:text_item).permit(:name, :itemtext, :text_id, :page_id, :order, :component_id, :template_component_id)
  end


end

app/helpers/text_item_helper.rb
module TextItemHelper
end

app/views/text_item/_pagetextitem.html.erb
<%= div_for pagetextitem do %>

  <%= pagetextitem.name %>: <strong><%= pagetextitem.itemtext %></strong>
  <%= link_to "(remove)", pagetextitem, method: :delete, data: {confirm: "Are you sure?"} %>
  <%= link_to "(update)", text_item_path(pagetextitem), remote: true %>
  <div id="form<%= pagetextitem.id %>" style="display:none;">
    <%= form_for pagetextitem, url: "/text_item/#{pagetextitem.id}", remote: true do |f| %>
      <%= f.hidden_field :_method, value: "patch" %>
      <%= f.hidden_field :id, value: pagetextitem.id %>
      <%= f.hidden_field :text_id, value: pagetextitem.text_id %>
      <%= f.hidden_field :component_id, :value => pagetextitem.component_id %>
      <%= f.hidden_field :page_id, :value => pagetextitem.page_id %>
      <%= f.hidden_field :order, :value => pagetextitem.order %>
      <%= f.hidden_field :name, :value => pagetextitem.name %>
      <%= f.text_field :itemtext %>
      <%= f.submit "Update" %>
    <% end %>
  </div>

<% end %>

app/views/text_item/_textitem.html.erb
<%= div_for textitem do %>

<%= textitem.name %> <%= link_to "(remove)", textitem, method: :delete, data: {confirm: "Are you sure?"} %> |
  <%= link_to "(new)", text_item_path(textitem), remote: true %>
  <div id="form<%= textitem.id %>" style="display:none;">
    <%= form_for @textitem, url: "/text_item/", remote: true do |f| %>
    <%= f.hidden_field :text_id, value: textitem.text_id %>
    <%= f.hidden_field :component_id, :value => textitem.component_id %>
    <%= f.hidden_field :page_id, :value => textitem. %>
    <%= f.hidden_field :order, :value => textitem.order %>
    <%= f.hidden_field :name, :value => textitem.name %>
    <%= f.text_field :itemtext %>
    <%= f.submit %>
  <% end %></div>

<% end %>

app/views/text_item/create.js.erb
$('#textitemlist').load(location.href+" #textitemlist>*", "");
$('#pagetextitemlist').load(location.href+" #pagetextitemlist>*", "");

app/views/text_item/destroy.js.erb
$('#edit_text_item_<%= @textitem.id %>').remove();

app/views/text_item/index.html.erb
<%  @component = Component.find(params[:id])
    @instance = TemplateComponent.find(params[:instance])
    @template = ::Template.find(params[:template])
    @site = Site.find(params[:site])
    @page = Page.find(params[:page]) %>

<div class="row">
  <div class="col-sm-3">

        <div style="margin-top: 20px;">
        <%= render "/pages/siteMap" %>
        </div>

    <h3 style="margin-top: 40px;">Structure</h3>

    <!-- Display Component relationships -->
          <p>Component: <br><%= @component.name %>
            <p>Instance: <br><%= @instance.id %>

              <% @page.templates.each do |a| %>
              <p>Template Components:
                <% @cinstance = TemplateComponent.order(:position).includes(:component, :template).references(:component, :template).where ({template_id: a.id}) %>
                <ol>
                  <!-- top version includes component instance ID for debugging -->
                  <%#= safe_join ( @cinstance.all.map { |x| ["<li>".html_safe, x.id, " ", link_to(x.component.name, text_item_index_path(:id => x.component.id, :instance => x.id, :template => x.template.id, :page => @thispage.id, :site => @site.id)),"</li>".html_safe] }) %>
                  <%= safe_join ( @cinstance.all.map { |x| ["<li>".html_safe, link_to(x.component.name, text_item_index_path(:id => x.component.id, :instance => x.id, :template => x.template.id, :page => @page.id, :site => @site.id)),"</li>".html_safe] }) %>
                </ol>
              <% end %>

              <p>Page: <br><%= link_to @page.name, page_path(:id => @page.id, :site => @site.id) %>
                <p>Template: <br><%= link_to @template.name, templatedetail_path(:id => @template.id, :site => @site.id ) %>
                  <p>Site: <br><%= link_to @site.name, sitemapdetail_path(:id => @site.id) %>

  </div>
  <div class="col-sm-9">
    <h1>Component</h1>
<!-- Component Copy for Specific Page -->
<hr>
<!-- <b>Component Items for Page</b> -->
<div id="pagetextitemlist">
  <table width="100%">

  <!-- C<%#= @component.id %><br>
  P<%#= @page.id %><br> -->
  <%# @pagetest = TextItem.order(:order).where ({page_id: @page.id, component_id: @component.id, template_component_id: @instance.id}) %>
  <!-- Debugging section
  <%# @pagetest.each do |t| %>
    <%#= t.id %> <%#= t.name %> / C<%#= t.component_id %> / P<%#= t.page_id %> /  instance<%#= t.template_component_id %> <br>
  <%# end %>
   -->

  <% @pagetext = TextItem.order(:order).where ({page_id: @page.id, component_id: @component.id, template_component_id: @instance.id}) %>
  <% @pagetext.each do |pagetextitem| %>
      <tr>
        <td>
        <<%= pagetextitem.text.name %>>
        <a href="#" style="color: #666;" data-toggle="tooltip" data-placement="top" title="<%= pagetextitem.name %>"><%= pagetextitem.itemtext %></a>
        </<%= pagetextitem.text.name %>>

          <div id="form<%= pagetextitem.id %>" style="display:none;">
            <%= form_for pagetextitem, url: "/text_item/#{pagetextitem.id}", remote: true do |f| %>
              <%= f.hidden_field :_method, value: "patch" %>
              <%= f.hidden_field :id, value: pagetextitem.id %>
              <%= f.hidden_field :text_id, value: pagetextitem.text_id %>
              <%= f.hidden_field :component_id, :value => pagetextitem.component_id %>
              <%= f.hidden_field :template_component_id, :value => pagetextitem.template_component_id %>
              <%= f.hidden_field :page_id, :value => pagetextitem.page_id %>
              <%= f.hidden_field :order, :value => pagetextitem.order %>
              <%= f.hidden_field :name, :value => pagetextitem.name %>
              <%= f.text_field :itemtext %>
              <%= f.submit "Update" %>
            <% end %>
          </div>
        </td>
        <td>
          <%= link_to "remove", text_item_path(:id => pagetextitem.id, :instance => @instance.id, :component => @component.id, :template => @template.id, :page => @page.id, :site => @site.id), method: :delete, data: {confirm: "Are you sure?"}, :class => "badge badge-warning" %>
              <%= link_to "update", text_item_path(pagetextitem), remote: true, :class => "badge badge-primary" %>
        </td>
      </tr>
    <% end %>
  </div>
  </table>
</div>

<!-- Component guidelines -->
<p>&nbsp;</p>
    <div class="card">
      <div class="card-header">
        <h3><%= @component.name %> <small class="text-muted">Component</small></h3>
      </div>
      <div class="card-body">


        <b>Component Template Items</b>

        <div id="textitemlist">
          <% @component.text_items.each do |textitem| %>
            <div>
              <%= textitem.name %> <!-- <%= link_to "(remove)", textitem, method: :delete, data: {confirm: "Are you sure?"} %> | -->
                <%= link_to "(new)", text_item_path(textitem), remote: true %>
                <div id="form<%= textitem.id %>" style="display:none;">
                  <%= form_for @textitem, url: "/text_item/", remote: true do |f| %>
                  <%= f.hidden_field :text_id, value: textitem.text_id %>
                  <%= f.hidden_field :component_id, :value => @component.id %>
                  <%= f.hidden_field :template_component_id, :value => @instance.id %>
                  <%= f.hidden_field :page_id, :value => @page.id %>
                  <%= f.hidden_field :order, :value => textitem.order %>
                  <%= f.hidden_field :name, :value => textitem.name %>
                  <%= f.text_field :itemtext %>
                  <%= f.submit %>
                <% end %></div>
            </div>
          <% end %>

        </div>

<br>


<table class="table table-hover" style="margin-top:30px;">
  <thead>
    <tr>
      <th scope="col">Attribute</th>
      <th scope="col">Description</th>
    </tr>
  </thead>
  <tbody>
    <% if @component.invision_link.blank? %>
    <% else %>
    <tr>
      <td valign="top"><small class="text-muted"><strong>Design Link</strong></small></td>
      <td><i><%= link_to @component.invision_link, @component.invision_link, target: "_blank" %></i></td>
    </tr>
    <% end %>

    <% if @component.image_sizes.blank? %>
    <% else %>
    <tr>
      <td valign="top"><small class="text-muted"><strong>Image Sizes</strong></small></td>
      <td valign="top"><small class="text-muted"><%= @component.image_sizes %></small></td>
    </tr>
    <% end %>

    <% if @component.page.blank? %>
    <% else %>
    <tr>
      <td valign="top"><small class="text-muted"><strong>Page</strong></small></td>
      <td valign="top"><small class="text-muted"><%= @component.page %></small></td>
    </tr>
    <% end %>

    <% if @component.requirements.blank? %>
    <% else %>
    <tr>
      <td valign="top"><small class="text-muted"><strong>Requirements</strong></small></td>
      <td valign="top"><small class="text-muted"><%=raw @component.requirements %></small></td>
    </tr>
    <% end %>

    <% if @component.interaction_notes.blank? %>
    <% else %>
    <tr>
      <td valign="top"><small class="text-muted"><strong>Interaction Notes</strong></small></td>
      <td valign="top"><small class="text-muted"><%=raw @component.interaction_notes %></small></td>
    </tr>
    <% end %>

    <% if @component.full_width.blank? %>
    <% else %>
    <tr>
      <td valign="top"><small class="text-muted"><strong>Full Width:</strong></td>
      <td valign="top"><small class="text-muted"><% if @component.full_width == 1 %>Yes<% else %>No<% end %></small></td>
    </tr>
    <% end %>

    <% if @component.personalization_rules.blank? %>
    <% else %>
    <tr>
      <td valign="top"><small class="text-muted"><strong>Personalization</strong></small></td>
      <td valign="top"><small class="text-muted"><%=raw @component.personalization_rules %></small></td>
    </tr>
    <% end %>

    <% if @component.data.blank? %>
    <% else %>
    <tr>
      <td valign="top"><small class="text-muted"><strong>Data</strong></small></td>
      <td valign="top"><small class="text-muted"><%=raw @component.data %></small></td>
    </tr>
    <% end %>

    <% if @component.allowed_controls.blank? %>
    <% else %>
    <tr>
      <td valign="top"><small class="text-muted"><strong>Allowed Controls</strong></small></td>
      <td valign="top"><small class="text-muted"><%=raw @component.allowed_controls %></small></td>
    </tr>
    <% end %>

    <% if @component.need_info.blank? %>
    <% else %>
    <tr>
      <td valign="top"><small class="text-muted"><strong>Need Info</strong></small></td>
      <td valign="top"><small class="text-muted"><% if @component.need_info == "x" %>Yes<% else %>No<% end %></small></td>
    </tr>
    <% end %>

    <% if @component.design_questions.blank? %>
    <% else %>
    <tr>
      <td valign="top"><small class="text-muted"><strong>Design Questions</strong></small></td>
      <td valign="top"><small class="text-muted"><%=raw @component.design_questions %></small></td>
    </tr>
    <% end %>

    <% if @component.dev_notes.blank? %>
    <% else %>
    <tr>
      <td valign="top"><small class="text-muted"><strong>Dev Notes</strong></small></td>
      <td valign="top"><small class="text-muted"><%=raw @component.dev_notes %></small></td>
    </tr>
    <% end %>
  </tbody>
</table>
      </div>
    </div>







</div>
</div>
<hr>
<div class="row">
<div class="col-sm">

          <%= render "/pages/footer" %>

</div>
</div>

app/views/text_item/show.js.erb
$("#form<%= params[:id] %>").show();

app/views/text_item/update.js.erb
// $('div#<%= dom_id(@textitem) %>').replaceWith('<%= j render partial: "pagetextitem", locals: {pagetextitem: @textitem} %>');
$('#pagetextitemlist').load(location.href+" #pagetextitemlist>*", "");