config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "pages#show", page: "home"

  get  '/component/:id', to: 'pages#component', as: 'component'
  get  '/components/', to: 'pages#components', as: 'components'
  get  '/contentmapping', to: 'pages#contentmapping'
  get  '/home', to: 'pages#home'
  get  '/flows', to: 'pages#flows'
  get  '/flowdetail/:id', to: 'pages#flowdetail', as: 'flowdetail'
  get  '/iframe', to: 'pages#iframe', as: 'iframe'
  get  '/legacysites', to: 'pages#legacysites'
  get  '/legacysitedetail/:id', to: 'pages#legacysitedetail', as: 'legacysitedetail'
  get  '/messaging', to: 'pages#messaging'
  get  '/messagingdetail/:id', to: 'pages#messagingdetail', as: 'messagingdetail'
  get  '/personachart/', to: 'pages#personachart', as: 'personachart'
  get  '/page/:id', to: 'pages#page', as: 'page'
  get   "/pages/:page" => "pages#show"
  get  '/searchtest', to: 'pages#searchtest'
  resources :search, only: [:index]
  resources :site_crawl
  get  '/sitemap', to: 'pages#sitemap'
  get  '/sitemapdetail/:id', to: 'pages#sitemapdetail', as: 'sitemapdetail'
  resources :sitepage
  get  '/smart_listing/' => 'smart_listing#index'
  get  '/taxonomy', to: 'pages#taxonomy'
  get  '/taxonomysite/:id', to: 'pages#taxonomysite', as: 'taxonomysite'
  get  '/templates', to: 'pages#templates'
  get  '/templatedetail/:id', to: 'pages#templatedetail', as: 'templatedetail'
  get  '/templatelist/:id', to: 'pages#templatelist', as: 'templatelist'
  resources :text_item
  get 'tree/' => 'tree#index'
  get 'tree/data', :defaults => { :format => 'json' }
  get 'tree/jcitags', :defaults => { :format => 'json' }
  get 'tree/tycotags', :defaults => { :format => 'json' }
  get 'tree/jcimap', :defaults => { :format => 'json' }
  get 'tree/tycomap', :defaults => { :format => 'json' }
  get  '/api/v1/tag/data', :defaults => { :format => 'json' }
  get  '/webfootprint', to: 'pages#webfootprint'
  #api
  namespace :api do
    namespace :v1 do
      # resources :sessions, only: [:create, :show]
      resources :tag, only: [:index, :create, :show, :update, :destroy] do
        post :activate, on: :collection
        # resource :feed, only: [:show]
      end
    end
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Content Cookbook | Johnson Controls</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'https://cdnjs.cloudflare.com/ajax/libs/d3/3.5.17/d3.min.js'%>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!--[if lt IE 9]>
          <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
          </script>
        <![endif]-->
    <style type="text/css">
        body{
        	padding-top: 70px;
        }
    </style>
    <meta charset="utf-8">

    <!-- Google Tag Manager -->
    <% if Rails.env.production? %>
    <script>
    document.addEventListener('turbolinks:load', function(event) {
      var url = event.data.url;  dataLayer.push({
        'event':'pageView',
        'virtualUrl': url
      });
    });(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
    new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
    j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
    'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
    })(window,document,'script','dataLayer','GTM-P76GQ78');
    </script>
    <% end %>
    <!-- End Google Tag Manager -->

  </head>

  <body>

    <!-- Google Tag Manager (noscript) -->
    <noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-P76GQ78"
    height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
    <!-- End Google Tag Manager (noscript) -->

    <nav id="myNavbar" class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top" role="navigation">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="container">
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>

        <%= link_to image_tag("http://contentmodel-jci-assets.s3.amazonaws.com/images/jci_logo_black_and_white.png", :alt => "Johnson Controls Content Plan", :style => "height:30px; margin: 0px 20px 0px 0px;") + "Content Cookbook", home_path, :class => "navbar-brand" %>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
          <ul class="nav navbar-nav mr-auto">
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Migration & Publishing</a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                <%#= link_to "Legacy Site List", legacysites_path, class: "dropdown-item" %>
                <%= link_to "Sitemap", sitemapdetail_path(1), class: "dropdown-item" %>
                <%= link_to "Taxonomy", taxonomysite_path(1), class: "dropdown-item" %>
                <%= link_to "Web Footprint (Sites)", webfootprint_path, class: "dropdown-item" %>
                <%#= link_to "Content Mapping", contentmapping_path, class: "dropdown-item" %>
              </div>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Creation</a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                <%= link_to "Content Model", templates_path, class: "dropdown-item" %>
                <%= link_to "Component List", components_path, class: "dropdown-item" %>
                <%#= link_to "Flows", flowdetail_path(1), class: "dropdown-item" %>
                <%= link_to "Messaging Hierarchy", messagingdetail_path(1), class: "dropdown-item" %>
                <!-- <a class="dropdown-item" href="#">SEO</a> -->
              </div>
            <!-- <li class="nav-item"><a class="nav-link" href="#">Governance</a></li>
            <li class="nav-item"><a class="nav-link" href="#">Measurement</a></li> -->
            <li class="nav-item"><a class="nav-link" href="/admin">Admin</a></li>
          </ul>

            <span class="navbar-text">
              <small>
              <% if admin_user_signed_in? %>
                Logged in as <strong><% if current_admin_user.first_name? %><%= current_admin_user.first_name %> <%= current_admin_user.last_name %><% else %><%= current_admin_user.email %><% end %></strong>
                <%#= link_to 'Edit profile', edit_admin_user_password_path, :class => 'navbar-link' %> |
                <%= link_to "Logout", destroy_admin_user_session_path, method: :delete, :class => 'navbar-link'  %>
              <% else %>
                <%= link_to "Sign up", new_admin_user_registration_path, :class => 'navbar-link'  %> |
                <%= link_to "Login", new_admin_user_session_path, :class => 'navbar-link'  %>
              <% end %></small>
            </span>
            <!-- </li> -->

            <!-- Alternative display of logged-in state; reference: https://guides.railsgirls.com/devise -->
            <!-- <p class="navbar-text pull-right"><small>
              <% if admin_user_signed_in? %>
                Logged in as <strong><%= current_admin_user.email %></strong>
                <%#= link_to 'Edit profile', edit_admin_user_password_path, :class => 'navbar-link' %> |
                <%= link_to "Logout", destroy_admin_user_session_path, method: :delete, :class => 'navbar-link'  %>
              <% else %>
                <%= link_to "Sign up", new_admin_user_registration_path, :class => 'navbar-link'  %> |
                <%= link_to "Login", new_admin_user_session_path, :class => 'navbar-link'  %>
              <% end %>
            </small></p> -->
        </div>
      </div>
    </nav>

    <div class="container">

      <% if notice %>
        <p class="alert alert-success"><%= notice %></p>
      <% end %>
      <% if alert %>
        <p class="alert alert-danger"><%= alert %></p>
      <% end %>

    <%= yield %>

  </div>
  </body>
</html>